### ISSUE TITLE
Missing screenshot

### ISSUE THREAD

**Issue by madskristensen** [ffMathy/shortcut-commander#1]
It would be awesome if you could put a screenshot up that shows what the UI looks like. That way I have a better understanding of what your extension does and what it looks like before trying it

**Comment by ffMathy** [comment]
Woah - a comment from the legendary @madskristensen!

Your word is my command. Will upload a screenshot on the page soon.

**Comment by ffMathy** [comment]
I added a screenshot now to the description page and this repository. 

Was that what you meant? Or did you mean the preview image in the manifest file?

Closing while I am awaiting your reply.

Tak for hjælpen! 😏

**Comment by ghost** [comment]
Would a gif showing the extension in action, not have been better?

**Comment by ffMathy** [comment]
That's a great idea!

**Comment by ffMathy** [comment]
GIF added. Thanks a lot @jonasjensen-brolstark!

**Comment by JohnyWS** [comment]
(for reference: Fixed in 14cb3cdc90e3 )

**Comment by ffMathy** [comment]
Thanks @JohnyWS!
