### ISSUE TITLE
Add support of Visual Studio 2022

### ISSUE THREAD

**Issue by BlackPower** [ffMathy/shortcut-commander#5]
It would be nice to add support for Visual Studio 2022

https://learn.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#modernize-your-vsix-project

**Comment by ffMathy** [comment]
I think it is already supported actually? 😅

**Comment by BlackPower** [comment]
No, it doesn't. I will create a PR

**Comment by ffMathy** [comment]
Aha. Yeah sorry about that, don't use VS anymore. Gone over to Rider. But thank you so much, and I'll have that merged! 👌👍

**Comment by BlackPower** [comment]
@ffMathy , could you please upload the extension for Visual Studio 2022 to the Visual Studio marketplace?
BTW, the project "ShortcutCommanderV17" can be compiled only in the x64 platform
